basic/controllers/TransactionsController.php
<?php

namespace app\controllers;

use app\models\Transactions;
use app\models\UserCredits;
use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;

class TransactionsController extends Controller {

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionSendCredits()
    {
        $tansaction = new Transactions();

        if ($tansaction->load(Yii::$app->request->post())) {
            $tansaction->type = $tansaction::TYPE_TRANSACTION;

            if ($tansaction->save()) {
                return $this->redirect(['site/index']);
            }
        }
        return $this->render('send-credits',['model' => $tansaction]);
    }

    public function actionSendBill()
    {
        $tansaction = new Transactions();

        if ($tansaction->load(Yii::$app->request->post())) {
            $tansaction->type = $tansaction::TYPE_BILL;

            if ($tansaction->save()) {
                return $this->redirect(['site/index']);
            }
        }
        return $this->render('send-bill',['model' => $tansaction]);
    }

    public function actionUserHistory()
    {

        $pendingBills = new ActiveDataProvider([
            'query' => Transactions::find()->where(['reciever_ip' => Yii::$app->user->identity->user_ip, 'type' => '1', 'status' => 10]),
            'pagination' => [
                'pageSize' => 20,

            ],
        ]);

        $doneBills = new ActiveDataProvider([
            'query' => Transactions::find()->where(['reciever_ip' => Yii::$app->user->identity->user_ip, 'type' => '1'])->andWhere('status < 10'),
            'pagination' => [
                'pageSize' => 20,

            ],
        ]);

        $pendingTransactions = new ActiveDataProvider([
            'query' => Transactions::find()->where(['reciever_ip' => Yii::$app->user->identity->user_ip, 'type' => '0', 'status' => 10]),
            'pagination' => [
                'pageSize' => 20,

            ],
        ]);

        $doneTransactions = new ActiveDataProvider([
            'query' => Transactions::find()->where(['reciever_ip' => Yii::$app->user->identity->user_ip, 'type' => '0'])->andWhere('status < 10'),
            'pagination' => [
                'pageSize' => 20,

            ],
        ]);

        return $this->render('user-notifications',[
            'pendingBills' => $pendingBills,
            'doneBills' => $doneBills,
            'pendingTransactions' => $pendingTransactions,
            'doneTransactions' => $doneTransactions
        ]);
    }

    public function actionAcceptBill($id)
    {
        $bill = Transactions::find()->where(['id' => $id])->one();
        $this->manipulateCredits($bill);
        return $this->redirect('user-history');
    }

    public function actionDeclineBill($id)
    {
        $bill = Transactions::find()->where(['id' => $id])->one();
        $bill->status = Transactions::STATUS_DECLINED;

        if ($bill->save()) {
            return $this->redirect('user-history');
        }
    }

    public function actionAcceptTransaction()
    {
        $post = Yii::$app->request->post();
        $transaction = Transactions::find()->where(['id' => $post['modelId']])->one();
        if ($transaction->protection_code == $post['protectionCode']) {
            $this->manipulateCredits($transaction);
        } else {
            Yii::$app->session->setFlash('danger', Yii::t('app','Invalid code'));
        }

        return $this->redirect('user-history');
    }

    public function actionDeclineTransaction($id)
    {
        $transaction = Transactions::find()->where(['id' => $id])->one();
        $transaction->status = Transactions::STATUS_DECLINED;

        if ($transaction->save()) {
            return $this->redirect('user-history');
        }
    }

    public function actionReturnTransaction($id)
    {
        $transaction = Transactions::find()->where(['id' => $id])->one();
        $this->manipulateCredits($transaction);
        return $this->redirect('user-history');

    }

    public function actionCreditsHistory() {

        return $this->render('credits-history');
    }

    public function actionBillsHistory() {

        return $this->render('bills-history');
    }

    public function manipulateCredits($transaction) {

        if (($transaction->type == $transaction::TYPE_BILL) && ($transaction->status == $transaction::STATUS_PENDING)) {
            $recieverCredits = UserCredits::find()->where(['user_ip' => $transaction->reciever_ip])->one();
            $recieverCredits->credits_count = $recieverCredits->credits_count - $transaction->credits;

            if ($recieverCredits->save()) {
                $senderCredits = UserCredits::find()->where(['user_ip' => $transaction->sender_ip])->one();
                $senderCredits->credits_count = $senderCredits->credits_count + $transaction->credits;

                if ($senderCredits->save()) {
                    $transaction->status = Transactions::STATUS_DONE;
                    $transaction->save();
                }

            }
        } elseif (($transaction->type == $transaction::TYPE_TRANSACTION) && ($transaction->status == $transaction::STATUS_DONE)) {
            $recieverCredits = UserCredits::find()->where(['user_ip' => $transaction->reciever_ip])->one();
            $recieverCredits->credits_count = $recieverCredits->credits_count - $transaction->credits;

            if ($recieverCredits->save()) {
                $senderCredits = UserCredits::find()->where(['user_ip' => $transaction->sender_ip])->one();
                $senderCredits->credits_count = $senderCredits->credits_count + $transaction->credits;

                if ($senderCredits->save()) {
                    $transaction->status = Transactions::STATUS_DECLINED;
                    $transaction->save();
                }

            }
        }

        elseif (($transaction->type == $transaction::TYPE_TRANSACTION) && ($transaction->status == $transaction::STATUS_PENDING)) {
                $recieverCredits = UserCredits::find()->where(['user_ip' => $transaction->reciever_ip])->one();
                $recieverCredits->credits_count = $recieverCredits->credits_count + $transaction->credits;

                if ($recieverCredits->save()) {
                    $senderCredits = UserCredits::find()->where(['user_ip' => $transaction->sender_ip])->one();
                    $senderCredits->credits_count = $senderCredits->credits_count - $transaction->credits;

                    if ($senderCredits->save()) {
                        $transaction->status = Transactions::STATUS_DONE;
                        $transaction->save();
                    }
                }
        }
    }

}

basic/views/transactions/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model frontend\models\Office */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="col-md-6">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'credits')?>

    <?= $form->field($model, 'reciever_ip')?>

    <?php if (Yii::$app->controller->action->id == 'send-credits') {

        echo $form->field($model, 'protected')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]);
    }
        ?>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app','Create'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/transactions/bills-history.php
<?php
use yii\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use app\models\Transactions;
use yii\grid\ActionColumn;

$transactions = new ActiveDataProvider([
    'query' => Transactions::find()->where(['sender_ip' => Yii::$app->user->identity->user_ip,'type' => 1])->orderBy(['id' => SORT_DESC]),
    'pagination' => [
        'pageSize' => 20,

    ],
]);

echo "<h4>СЧЕТА:</h4>";
echo GridView::widget([
    'dataProvider' => $transactions,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        'status' => [
            'label' => 'Статус',
            'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
                if ($data->status == 1) {
                    return "Отклонен";
                } elseif ($data->status == 10) {
                    return "Ожидает подтверждения";
                } else {
                    return "Подтвержден";
                }

            },
        ],
    ]
]);

basic/views/transactions/credits-history.php
<?php
use yii\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use app\models\Transactions;
use yii\grid\ActionColumn;

$transactions = new ActiveDataProvider([
    'query' => Transactions::find()->where(['sender_ip' => Yii::$app->user->identity->user_ip,'type' => 0])->orderBy(['id' => SORT_DESC]),
    'pagination' => [
        'pageSize' => 20,

    ],
]);

echo "<h4>ПЕРЕВОДЫ:</h4>";
echo GridView::widget([
    'dataProvider' => $transactions,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        'status' => [
            'label' => 'Статус',
            'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
                if ($data->status == 1) {
                    return "Отклонен";
                } elseif ($data->status == 10) {
                    return "Ожидает подтверждения";
                } else {
                    return "Подтвержден";
                }

            },
        ],
    ]
]);

basic/views/transactions/send-bill.php
<?= $this->render('_form', [
    'model' => $model,
]) ?>

basic/views/transactions/send-credits.php
<?= $this->render('_form', [
    'model' => $model,
]) ?>

basic/views/transactions/user-history.php
<?php
/**
 * Created by PhpStorm.
 * User: alexander
 * Date: 28.03.16
 * Time: 11:50
 */

basic/views/transactions/user-notifications.php
<?php
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\models\Transactions;
use yii\grid\ActionColumn;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

echo "<h3 class='text-center'>Ожидающие подтверждения:</h3>";
echo "<h4>СЧЕТА:</h4>";
echo GridView::widget([
    'dataProvider' => $pendingBills,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        [
            'class' => ActionColumn::className(),
            'template' => '{accept} {decline}',
            'buttons' => [
                'accept' => function ($url, $model) {
                    return Html::a('Accept', ['transactions/accept-bill','id' => $model->id], ['class' => 'btn btn-success']);
                },

                'decline' => function ($url, $model) {
                    return Html::a('Decline', ['transactions/decline-bill','id' => $model->id], ['class' => 'btn btn-danger']);
                }

            ],
        ],
    ]
]);
echo "<h4>ПЕРЕВОДЫ:</h4>";
echo GridView::widget([
    'dataProvider' => $pendingTransactions,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        [
            'class' => ActionColumn::className(),
            'template' => '{accept} {decline}',
            'buttons' => [
                'accept' => function ($url, $model) {
                    return Html::a('Accept',null, ['class' => 'btn btn-success', 'data-toggle' => 'modal','data-model-id' => $model->id, 'data-target' => '#myModal']);
                },

                'decline' => function ($url, $model) {
                    return Html::a('Decline', ['transactions/decline-transaction','id' => $model->id], ['class' => 'btn btn-danger']);
                }

            ],
        ],
    ]
]);


echo "<h3 class='text-center'>Подтвержденные:</h3>";
echo "<h4>ПЕРЕВОДЫ:</h4>";
echo GridView::widget([
    'dataProvider' => $doneTransactions,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        'status' => [
            'label' => 'Статус',
            'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
                if ($data->status == 1) {
                    return "Отклонен";
                } else {
                    return "Подтвержден";
                }

            },
        ],
        [
            'class' => ActionColumn::className(),
            'template' => '{return}',
            'buttons' => [
                'return' => function ($url, $model) {
                    if ($model->status == 0) {
                        return Html::a('Вернуть', ['transactions/return-transaction','id' => $model->id], ['class' => 'btn btn-danger']);
                    }
                }

            ],
        ],
    ]
]);

echo "<h4>СЧЕТА:</h4>";
echo GridView::widget([
    'dataProvider' => $doneBills,
    'summary' => '',
    'columns' => [
        'sender_ip',
        'reciever_ip',
        'credits',
        'created_at:datetime',
        'status' => [
            'label' => 'Статус',
            'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
            'value' => function ($data) {
                if ($data->status == 1) {
                    return "Отклонен";
                } else {
                    return "Подтвержден";
                }

            },
        ],
        ]

]);

?>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <form action="<?= \yii\helpers\Url::toRoute(['transactions/accept-transaction']) ?>" enctype="multipart/form-data" method="post">
                    <?= Html::label('Enter Code here') ?>
                    <?= Html::input('string','protectionCode',null,['class' => 'form-control']) ?>
                    <?= Html::hiddenInput('modelId',null,['class' => 'form-control']) ?>
                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('app','Submit'), ['class' => 'btn btn-primary']) ?>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>